jobs:
  include:
  - dist: xenial
    os: linux
  - dist: trusty 
    os: linux
  - dist: bionic
    os: linux
  - os: osx
  - os: windows
language: c
compiler: gcc
os: linux
dist: xenial

before_install:
  - export FILE_ROOT="protobufkdb"
  - export TESTS="True"
  - export BUILD="True"

  # Run instructions to install the C/C++ requirements (BUILD_HOME) set in place of PAHO_HOME/HDF5_HOME etc.
  # Files in this case are unzipped into cbuild within travis_setup.sh
  - if [[ $BUILD == "True" ]]; then
      chmod +x travis_setup.sh; 
      ./travis_setup.sh;
      export BUILD_HOME=$TRAVIS_BUILD_DIR/cbuild/install;
      export LIB="cmake/$FILE_ROOT/lib";
      mkdir cmake;
    else
      export LIB="";
    fi

  # Download vcpkg
  - git clone https://github.com/microsoft/vcpkg
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      ./vcpkg/bootstrap-vcpkg.bat;
    else
      ./vcpkg/bootstrap-vcpkg.sh;
    fi
    
  # Use vcpkg to build and install protobuf for the required OS
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      ./vcpkg/vcpkg install protobuf:x64-linux-rel;
      QLIBDIR=l64; OD=$L64;
    elif [[ $TRAVIS_OS_NAME == "osx" ]]; then
      ./vcpkg/vcpkg install protobuf:x64-osx-rel;
      QLIBDIR=m64; OD=$M64;
    elif [[ $TRAVIS_OS_NAME == "windows" ]]; then
      ./vcpkg/vcpkg.exe install protobuf:x64-windows-static;
      QLIBDIR=w64; OD=$W64;
    else
      echo "unknown OS ('$TRAVIS_OS_NAME')" >&2; exit 1;
    fi

  - export QLIBDIR
  - mkdir qhome;
  - export QHOME=$(pwd)/qhome;
  - export PATH=$QHOME/$QLIBDIR:$PATH;
  
  # Set up q for testing and execute tests on multiple 
  - if [[ $TESTS == "True" && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      export LD_LIBRARY_PATH=$BUILD_HOME/lib:$LD_LIBRARY_PATH;
      export DYLD_LIBRARY_PATH=$BUILD_HOME/lib:$LD_LIBRARY_PATH;
      export PATH=$BUILD_HOME/lib:$PATH;
      curl -u $NEXUS_USER:$NEXUS_PASS -o qhome/q.zip -L $OD;
      unzip -d qhome qhome/q.zip;
      rm qhome/q.zip;
      echo -n $QLIC_KC |base64 --decode > qhome/kc.lic;
    else
      echo No kdb+, no tests;
    fi

  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      export FILE_TAIL="zip";
    else
      export FILE_TAIL="tgz";
    fi
  - export FILE_NAME=$FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.$FILE_TAIL

  # Make binaries for the library as appropriate
  
  # Use vckpg toolchain to find protobuf
  - if [[ $BUILD == "True" && $TRAVIS_OS_NAME == "windows" ]]; then
      cd cmake && cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake .. ;
      cmake --build . --config Release;
      cmake --build . --config Release --target install;
      cd ..;
    elif [[ $BUILD == "True" && ( $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ) ]]; then
      cd cmake && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake && make install && cd .. ;
    fi

script:
  # The tests neeed to be run from the package directory since they need to dynamically import Google's .proto files
  - if [[ $TESTS == "True" && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      cd ./cmake/$FILE_ROOT; 
      curl -o test.q -L https://github.com/KxSystems/hdf5/raw/master/test.q;
      q test.q tests/ -q;
      cd -;
    fi
  - if [[ $TRAVIS_OS_NAME == "windows" && $BUILD == "True" ]]; then
      7z a -tzip -r $FILE_NAME ./cmake/$FILE_ROOT/*;
    elif [[ $BUILD == "True" && ( $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ) ]]; then  
      tar  -zcvf $FILE_NAME -C cmake/$FILE_ROOT .;
    elif [[ $TRAVIS_OS_NAME == "windows" ]]; then
      7z a -tzip $FILE_NAME README.md install.bat LICENSE q examples proto;
    elif [[ $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ]]; then
      tar  -zcvf $FILE_NAME README.md install.sh LICENSE q examples proto;
    fi

deploy:
  provider: releases
  token: "$GITHUB_APIKEY"
  file: "$FILE_NAME"
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = windows || $TRAVIS_OS_NAME = osx || ($TRAVIS_DIST = trusty && $TRAVIS_OS_NAME = linux) 
  skip_cleanup: 'true'
  